name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        grammar: [1]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Install test harness dependency
        run: pip install pytest

      - name: Build your compiler
        run: sbt compile

      - name: Run tests for grammar ${{ matrix.grammar }}
        run: python3 test/run_tests.py --stage lexer --grammar ${{ matrix.grammar }} --no-build
